obj-$(CONFIG_AE3069) = ae3069/
obj-$(CONFIG_EDOSK2674) = edosk2674/
obj-$(CONFIG_H8MAX) = h8max/
obj-$(CONFIG_H8300H_SIM) = h8300h_sim/
obj-$(CONFIG_H8S_SIM) = h8s_sim/
obj-$(CONFIG_KANEBEBE) = kanebebe/
