#
# arch/rx/Makefile
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# (C) Copyright 2009 Yoshinori Sato <ysato@users.sourceforge.jp>
#

KBUILD_CFLAGS += $(cflags-y)
KBUILD_CFLAGS += -g
KBUILD_CFLAGS += -D__linux__
KBUILD_CFLAGS += -DUTS_SYSNAME=\"uClinux\"
LDFLAGS += $(ldflags-y)
LDFLAGS += --no-flag-mismatch-warnings

LIBGCC := $(shell $(CROSS-COMPILE)$(CC) $(KBUILD_CFLAGS) -print-libgcc-file-name)

core-y	+= arch/$(ARCH)/kernel/ \
	   arch/$(ARCH)/mm/ \
           arch/$(ARCH)/boards/ \
	   arch/$(ARCH)/lib/ 
libs-y	+= $(LIBGCC)

boot := arch/$(ARCH)/boot

archmrproper:

archclean:
	$(Q)$(MAKE) $(clean)=$(boot)

vmlinux.srec vmlinux.bin zImage uImage: vmlinux
	$(Q)$(MAKE) $(build)=$(boot) $(boot)/$@

define archhelp
  @echo  'vmlinux.bin  - Create raw binary'
  @echo  'vmlinux.srec - Create srec binary'
  @echo  'zImage       - Compressed kernel image'
endef
