/* 
 * arch/arm/mach-fm3/include/mach/debug-macro.S
 *
 * Debugging macro include header
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

	.macro	addruart,rx,tmp
	.endm

	.macro	senduart,rd,rx
	.endm
	
	.macro	busyuart, rd, rx
	.endm

	.macro	waituart, rd, rx
	.endm
